"""
SehatSaathi — Fixed Response Templates
These templates are used VERBATIM. They are never generated by any model.
Every response must end with the disclaimer line. This is mandatory.
"""

from backend.config import EMERGENCY_NUMBER


def greeting_message() -> str:
    """First message sent to a new user."""
    return (
        f"Hi, this is SehatSaathi. Send a voice note describing what's wrong and I'll "
        f"help you figure out the right next step. This is not a doctor — for emergencies "
        f"always call {EMERGENCY_NUMBER}."
    )


def emergency_message(clinic_name: str = "nearest hospital", clinic_address: str = "") -> str:
    """
    Emergency template — used when keyword override fires OR model classifies as emergency.
    """
    location = f"{clinic_name}"
    if clinic_address:
        location += f", {clinic_address}"

    return (
        f"This may be a medical emergency. Please call {EMERGENCY_NUMBER} or go to the "
        f"nearest hospital right now: {location}. "
        f"This message is not a diagnosis."
    )


def soon_message(
    transcript_summary: str,
    clinic_name: str = "nearest clinic",
    open_hours: str = "",
) -> str:
    """Should be seen by a doctor within a few days."""
    hours_text = f", open {open_hours}" if open_hours else ""
    return (
        f"Based on what you shared: {transcript_summary}\n"
        f"This should be checked by a doctor in the next few days, not urgently "
        f"tonight. Nearest option: {clinic_name}{hours_text}. "
        f"This is not a diagnosis — please see a doctor to confirm."
    )


def monitor_message(transcript_summary: str, advice_text: str = "") -> str:
    """Mild symptoms, can be watched at home."""
    advice = f": {advice_text}" if advice_text else "."
    return (
        f"Based on what you shared: {transcript_summary}\n"
        f"This sounds mild and can likely be watched at home for now{advice} "
        f"If it gets worse or doesn't improve in a couple of days, please see a doctor. "
        f"This is not a diagnosis."
    )


# Simple advice lookup for common mild symptoms
MONITOR_ADVICE = {
    "headache": "Rest, stay hydrated, and take a mild painkiller if needed",
    "cold": "Rest, drink warm fluids, and keep warm",
    "cough": "Stay hydrated, try warm honey water, rest your voice",
    "fever": "Rest, stay hydrated, and monitor your temperature",
    "body ache": "Rest and gentle stretching may help",
    "stomach": "Eat light, bland food and stay hydrated",
    "diarrhea": "Drink plenty of fluids to avoid dehydration, eat bland food",
    "nausea": "Sip water slowly, avoid heavy meals, rest",
    "sore throat": "Gargle with warm salt water, drink warm fluids",
    "runny nose": "Stay hydrated, rest, use a warm compress",
}


def get_advice_for_symptoms(transcript_text: str) -> str:
    """Look up simple advice based on keyword matching in transcript."""
    text = transcript_text.lower()
    for keyword, advice in MONITOR_ADVICE.items():
        if keyword in text:
            return advice
    return "Rest and monitor your symptoms"
